source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HamburgerButton_Example', :exclusive => true do
  pod "HamburgerButton", :path => "../"
end

target 'HamburgerButton_Tests', :exclusive => true do
  pod "HamburgerButton", :path => "../"

  
end
